### ISSUE TITLE
CamelCase again

### ISSUE THREAD

**Issue by VitalyName** [protobufjs/protobuf.js#1130] opened 2018-10-31 05:10 UTC
protobuf.js version: 6.8.8

<please describe the expected and actual behavior>

I found problem with camelcase where  _  before digit. If the field name was "aaa_bbb_1_ccc", then after generation it turns out to be aaaBbb_1Ccc. But why is here second "_" (before digit)?

**Comment by Jhowden** [comment] 2018-11-05 17:09
Just hit this as well. Is this a regression?

**Comment by alexander-fenster** [comment] 2019-05-24 22:37
Hi @VitalyName and @Jhowden,

The main problem with the requests like that, as discussed in #1154, is that these changes are not just bug fixes, but are actually breaking changes so I feel we cannot do anything like that without bumping a major version; we don't know if any existing code breaks after doing that. I think, previously, the change related to such field names happened when moving from v5 to v6 which was a major version update. So even if it's clearly a bug, we might as well just leave it there for now.

(I'll close this issue since it's essentially a duplicate of #1009 which was filed earlier)

**Closed by alexander-fenster** 2019-05-24 22:37 UTC
Labels: duplicate
