### ISSUE TITLE
error 404, unable to install protobufjs

### ISSUE THREAD

**Issue by trusktr** [protobufjs/protobuf.js#1057] opened 2018-05-29 23:30 UTC
Looks like I'm not the only one getting this error with `prototbufjs` over time:

- https://github.com/dcodeIO/protobuf.js/issues/979
- https://github.com/dcodeIO/protobuf.js/issues/579

Seems like a problem with npmjs.com.

Example:

```
❯ npm i protobufjs@5
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@5

┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /Users/trusktr/.config │
└────────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trusktr/.npm/_logs/2018-05-29T23_30_22_244Z-debug.log
```

**Comment by trusktr** [comment] 2018-05-29 23:39
This is happening to me right now on npm v5.6.0 and v6.1.0.

**Comment by Negan1911** [comment] 2018-05-29 23:50
Duplicate of #1056

**Comment by issackpgit** [comment] 2018-05-30 00:28
This is happening to me also. npm v6.1.0

**Comment by artz** [comment] 2018-05-30 01:48
Yup. 
```1724 verbose stack Error: 404 Not Found: protobufjs@^6.8.0
1724 verbose stack     at fetch.then.res (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
1724 verbose stack     at tryCatcher (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
1724 verbose stack     at Promise._settlePromiseFromHandler (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
1724 verbose stack     at Promise._settlePromise (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
1724 verbose stack     at Promise._settlePromise0 (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
1724 verbose stack     at Promise._settlePromises (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
1724 verbose stack     at Async._drainQueue (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
1724 verbose stack     at Async._drainQueues (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
1724 verbose stack     at Immediate.Async.drainQueues (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
1724 verbose stack     at runCallback (timers.js:789:20)
1724 verbose stack     at tryOnImmediate (timers.js:751:5)
1724 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
1725 verbose cwd /Users/artz/Sites/lightbox
1726 verbose Darwin 17.5.0
1727 verbose argv "/Users/artz/.nvm/versions/node/v8.9.1/bin/node" "/Users/artz/.nvm/versions/node/v8.9.1/bin/npm" "install"
1728 verbose node v8.9.1
1729 verbose npm  v5.6.0
1730 error code E404
1731 error 404 Not Found: protobufjs@^6.8.0
1732 verbose exit [ 1, true ]```

**Comment by zuohuadong** [comment] 2018-05-30 02:52
npm --registry https://registry.npm.taobao.org install protobufjs@5

**Comment by shobhit13** [comment] 2018-05-30 02:59
OMG THANK YOU! @zuohuadong you helped me so much with this fix!

**Comment by dannypaz** [comment] 2018-05-31 06:27
@trusktr Can you verify that the issue has been resolved? See https://github.com/dcodeIO/protobuf.js/issues/1056#issuecomment-393250053 for more info.

**Comment by scream314** [comment] 2018-05-31 15:34
I still get a 404 :(

**Comment by cconcise** [comment] 2018-05-31 21:40
I'm still getting a 404 as well

**Comment by scream314** [comment] 2018-06-01 11:27
After updating NPM to 6.x.x protobuf was found and installed, but now I have other errors. Surprisingly YARN can install my dependencies without issues...

**Comment by nicolasnoble** [comment] 2018-06-01 17:06
This is an npm issue, not a protobufjs issue.

**Closed** 2019-04-22 04:38 UTC
